maps:
  arena:
    name: "Arena"
    folder: "1"
    time: 0
    red: #red spawn pos
      x: 0.5
      y: 69
      z: -31.5
    blue: #blue spawn pos
      x: 0.5
      y: 69
      z: 31.5

kits:
  buhc:
    # item format id:meta(enchId:enchLvl,anotherEnch)-count
    hp: 40
    helmet: "306:0(0:3)"
    chestplate: "307:0(0:3)"
    leggings: "308:0(0:3)"
    boots: "309:0(0:3)"
    items: ["267:0(9:1)","322:0-5"]
    maps: ["arena"]
    ac: 5
    kb: 0.3

title: "§2§lDUEL" #scoreboard title
scoreboard:
  - "--------------"
  - "Map: %map%"
  - "Against: %against%"
  - "--------------."
  - "§e§lFINALGAME.CN"